version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2005:2005"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped 